### ISSUE TITLE
[question] FormatMessage

### ISSUE THREAD

**Issue by mubix** [p0dalirius/win32errorcodes#1]
For C, does FormatMessage not work for this? 

Pretty sure I've used this exact StackOverflow many times in my coding career:
```cpp
wchar_t buf[256];
FormatMessageW(FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS,
               NULL, GetLastError(), MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT), 
               buf, (sizeof(buf) / sizeof(wchar_t)), NULL);
```
https://stackoverflow.com/a/17386923

**Comment by p0dalirius** [comment]
Hey!

Yes it works but not in all the cases. I found that when working with RPC a lot of errors are not parsed correctly (no error string) with this method. **Edit:** I used this function when I first encountered missing error messages:

```c
// Returns the last Win32 error, in string format. Returns an empty string if there is no error.
void PrintWin32Error(DWORD dwError)
{
	LPWSTR messageBuffer = NULL;
	size_t size = FormatMessage(FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS,
		NULL, dwError, MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT), (LPWSTR)&messageBuffer, 0, NULL);

	wprintf(L"[!] Error 0x%08x - %s", dwError, messageBuffer);
	// Free the buffer.
	LocalFree(messageBuffer);
}
```

Thats why I created this awful exhaustive library haha

Best regards,

**Comment by p0dalirius** [comment]
For some reason, I cannot find the edge case I was in where I got Unknown errors.

I agree with you it seems it resolves the same things as I did, so this library is not useful. I am sure I did it for a reason, I should have written more info at the time.

**Comment by p0dalirius** [comment]
Hey,

In a CPP code, I used both [win32errorcodes](https://github.com/p0dalirius/win32errorcodes) library and the following function:

```cpp
// https://stackoverflow.com/a/17386923
wchar_t errormessage[4096];
FormatMessageW(
    FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS, // dwFlags
    NULL,                                                       // lpSource
    result,                                                     // dwMessageId
    MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT),                  // dwLanguageId
    errormessage,                                               // lpBuffer
    (sizeof(errormessage) / sizeof(wchar_t)),                   // nSize
    NULL                                                        // *Arguments
);
wprintf(L"[error] %ls returned (%d): %ls\r\n", function, result, errormessage);
```

## With `FormatMessageW()`:

![image](https://github.com/p0dalirius/win32errorcodes/assets/79218792/30c5a351-87c1-4d8e-8bc2-2f258c456c7b)

## With [win32errorcodes](https://github.com/p0dalirius/win32errorcodes) library:

![image](https://github.com/p0dalirius/win32errorcodes/assets/79218792/7c6a28ce-3207-42ae-9ddf-47e0e0e80b9c)

`ERROR_BAD_IMPERSONATION_LEVEL` is apparently not resolved by `FormatMessageW()` in this case.

Honestly I wrote this library to be able to print exhaustive details on various error codes, but if there is a way to do it properly using builtin functions, I'd rather do this! I found that in some cases (like here) some errors are not printed, and when I'm doing research, it annoys me a lot to waste time on this 😂

I am closing the issue for now, but @mubix I am very interested if you know a way to do it properly using builtin functions!

Best regards,
